//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesanMakanan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makanan
    {
        public int IDMakanan { get; set; }
        public string NamaMakanan { get; set; }
        public string TipeMakanan { get; set; }
        public string Gambar { get; set; }
        public int Harga { get; set; }
    }
}
