//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesanMakanan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Pesanan
    {
        public int IDPesanan { get; set; }
        [Display(Name ="ID Makanan")]
        public int IDMakanan { get; set; }

        [Display(Name = "ID Toko")]
        public int IDToko { get; set; }
        public int IDUser { get; set; }

        [Required(ErrorMessage ="This field is required")]
        public int Jumlah { get; set; }
        public int TotalHarga { get; set; }
        public int Status { get; set; }
    }
}
